-- MySQL Script generated by MySQL Workbench
-- 11/19/16 08:58:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `idt_country` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nme_country` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idt_country`)  COMMENT '',
  UNIQUE INDEX `idt_country_UNIQUE` (`idt_country` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avatar` (
  `idt_avatar` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nme_avatar` VARCHAR(45) NOT NULL COMMENT '',
  `url_avatar` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`idt_avatar`)  COMMENT '',
  UNIQUE INDEX `idt_avatar_UNIQUE` (`idt_avatar` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idt_user` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nme_user` VARCHAR(45) NOT NULL COMMENT '',
  `nick_user` VARCHAR(45) NOT NULL COMMENT '',
  `gender_user` VARCHAR(1) NOT NULL COMMENT '',
  `email_user` VARCHAR(45) NOT NULL COMMENT '',
  `pass_user` VARCHAR(45) NOT NULL COMMENT '',
  `priv_user` VARCHAR(1) NOT NULL DEFAULT 'u' COMMENT '',
  `col_country` INT NOT NULL COMMENT '',
  `col_avatar` INT NOT NULL COMMENT '',
  `registration_ip_user` VARCHAR(45) NOT NULL COMMENT '',
  `last_login_ip_user` VARCHAR(45) NULL COMMENT '',
  `active` VARCHAR(1) NOT NULL DEFAULT 'y' COMMENT '',
  PRIMARY KEY (`idt_user`)  COMMENT '',
  INDEX `fk_user_country_idx` (`col_country` ASC)  COMMENT '',
  INDEX `fk_user_avatar1_idx` (`col_avatar` ASC)  COMMENT '',
  UNIQUE INDEX `email_user_UNIQUE` (`email_user` ASC)  COMMENT '',
  UNIQUE INDEX `idt_user_UNIQUE` (`idt_user` ASC)  COMMENT '',
  CONSTRAINT `fk_user_country`
    FOREIGN KEY (`col_country`)
    REFERENCES `mydb`.`country` (`idt_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_avatar1`
    FOREIGN KEY (`col_avatar`)
    REFERENCES `mydb`.`avatar` (`idt_avatar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anti_flood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anti_flood` (
  `idt_anti_flood` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ip_user` VARCHAR(45) NOT NULL COMMENT '',
  `time` DATETIME NOT NULL COMMENT '',
  `count` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idt_anti_flood`)  COMMENT '',
  UNIQUE INDEX `idt_anti_flood_UNIQUE` (`idt_anti_flood` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game1` (
  `idt_game1` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idt_user` INT NOT NULL COMMENT '',
  `user_score` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`idt_game1`)  COMMENT '',
  UNIQUE INDEX `idt_user_UNIQUE` (`idt_user` ASC)  COMMENT '',
  UNIQUE INDEX `idt_game1_UNIQUE` (`idt_game1` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banned_ip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banned_ip` (
  `idt_ip` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ip_number` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idt_ip`)  COMMENT '',
  UNIQUE INDEX `idt_ip_UNIQUE` (`idt_ip` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
